POST https://api.perplexity.ai/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "sonar",
  "messages": [
    {
      "role": "system",
      "content": "Be precise and concise."
    },
    {
      "role": "user",
      "content": "How many stars are there in our galaxy?"
    }
  ]
}
