import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import HeaderPage from "@/components/ui/header/pages/HeaderPage";
import TranslationProvider from "@/components/TranslationsProvider";
import initTranslations from "../i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const i18nNameSpaces = ["home"];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  const { locale } = await params;
  const { resources } = await initTranslations(locale, i18nNameSpaces);

  return (
    <ViewTransitions>
      <html lang="kr">
        <head>
          <link
            rel="preload"
            as="image"
            href="/main_bg.jpg"
            fetchPriority="high"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TranslationProvider
            resources={resources}
            locale={locale}
            namespaces={i18nNameSpaces}
          >
            <HeaderPage />
            {children}
          </TranslationProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
